### ISSUE TITLE
golang builds are not from a verifiable source

### ISSUE THREAD

**Issue by pdbogen** [bitnami/bitnami-docker-golang#3]
Howdy.

The docker image builds as described in this repo are pulling pre-compiled binaries from some source, but the source is not upstream Golang.

The checksums that the docker image builds are validating do not match upstream golang checksums.

It would provide a better certainity of supply chain integrity if these images pulled pre-compiled Go binaries and libraries directly from golang.org.

Thanks,
- Patrick

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. We are using the binaries here https://github.com/golang/go/releases. Could you let us know which process you used for checking the image checksums? We would like to understand which was the difference you saw.

**Comment by pdbogen** [comment]
Howdy- thanks for the quick response!

According to the [Dockerfile](https://github.com/bitnami/bitnami-docker-golang/blob/master/1.16/debian-10/Dockerfile), the golang binaries are retrieved from `https://downloads.bitnami.com/files/stacksmith/golang-1.16.5-0-linux-amd64-debian-10.tar.gz` and (at this moment) would have checksum `71b609596e2fd9a017408e89667d5eed7975a7716e84e9146282562ff84c3d4a`.

I can't find any information about how/where the package on `downloads.bitnami.com` is built, so to me, this is not an easily trusted supply chain. The archive in question _does not_ have the same checksum (`71b60959…`) as the archive on https://github.com/golang/go/releases, which in any case, is a soruce code archive.

The downloads.bitnami.com archive also appears to have a variety of bitnami metadata of somewhat unknown purpose/provenance in it.

I'd feel a lot better about a Dockerfile that directly retrieved the Golang-provided binaries from golang.org, similar to the [way in which Docker Hub's `golang` images are built](https://github.com/docker-library/golang/blob/master/1.16/buster/Dockerfile#L27-L30).

**Comment by javsalgar** [comment]
Hi,
Thanks for the feedback and concerns you shared with us.

The checksum in the tarball changes because we add some extra files like the license and other metadata for our containers. However, if you enter the files/ folder inside the tarball and compare with the upstream go tarball, you will see that the checksums are the same.

```
48fa9595f6835ae5ff64321dbe49dad4da84d632110bd444ba11293b04322ea9  gofmt (upstream)
48fa9595f6835ae5ff64321dbe49dad4da84d632110bd444ba11293b04322ea9  gofmt (bitnami)
0fd0bd8975892bda19a587168b12cfe717c3f8f692cb7170249b6d560d328cd8 go (upstream)
0fd0bd8975892bda19a587168b12cfe717c3f8f692cb7170249b6d560d328cd8  go (bitnami)
```

Having said this, for other artifacts we compile the source code, and at some point, that could be the case for go. So in general I'd say that we, VMware, position ourselves as a trusted proxy for packaging open source projects, with the added value of a wide range of analyses we perform: upstream project health, anti-virus scanning, CVE scanning, functional and verification testing, secure configurations, .. amongst others.

So the short answer is that if you want to use our packaging, you should accept VMware as a trusted source of artifacts, a trusted software supply chain, the same way you accept Debian or other distros as a trusted source when using their distros.

Let us know if there is anything you may think of that can help you on this, and we will evaluate its feasibility.

**Comment by pdbogen** [comment]
Thanks for that context. Regardless of what (if anything) y'all opt to do here, I want to say that I appreciate the willingness to chat about it.

I don't, per se, distrust VMWare/Bitnami to provide these packages, but it would be valuable if it were possible to visually inspect the source code to ascertain the provenance.

Specifically, here- how can I observe that the package pulled from `https://downloads.bitnami.com/files/stacksmith/golang-1.16.5-0-linux-amd64-debian-10.tar.gz` are built from upstream Golang binaries? Is there somewhere I can read the build process / build output, in the same way that I can read the Dockerfile, in this repo?

I think this is an even bigger concern if/when you start to build Go binaries from source code, because then the checksums of files in the archive likely won't match, as they do today.

I think this process is much easier if the Dockerfile directly pulls from golang.org and verifies the same hash as listed on golang.org's site, even if it then layers on some bitnami-related metadata.

I think we have similar goals here- I'm looking to be able to make a stronger statement about the trustworthiness of this image, and I'd prefer not to have a link in that chain of trust be "and then VMWare tells us that this URL is trustworthy."

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback. So, if I understood correctly, it would be great if we could share the build process and output, so you understand how this tarball is generated, right? 

I will open an internal task for discussion. We cannot guarantee an ETA on this as it will require several changes in our side. However, as soon as we have more news, we will update the ticket.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
